### ISSUE TITLE
About the implementation with the CLIP model

### ISSUE THREAD

**Issue by Xyuqiao** [KHU-AGI/PriViLege#5]
Could you release the code for the implementation using the CLIP model?

**Comment by pgh2874** [comment]
Regrettably, I can't release the code regarding CLIP due to internal reasons. However, we used the CLIP model from [OpenCLIP](https://github.com/mlfoundations/open_clip). You can modify our code from ViT to CLIP without much effort using OpenCLIP.

**Comment by Xyuqiao** [comment]
> Regrettably, I can't release the code regarding CLIP due to internal reasons. However, we used the CLIP model from [OpenCLIP](https://github.com/mlfoundations/open_clip). You can modify our code from ViT to CLIP without much effort using OpenCLIP.

Ok, so can you provide details of your implementation, including base/ incremental learning rate, epoch, etc?

**Comment by hxphieno** [comment]
I also encountered this situation. One possibility is that your python version is not 3.8. Just change it to 3.8.

**Comment by pgh2874** [comment]
> > Regrettably, I can't release the code regarding CLIP due to internal reasons. However, we used the CLIP model from [OpenCLIP](https://github.com/mlfoundations/open_clip). You can modify our code from ViT to CLIP without much effort using OpenCLIP.
> 
> Ok, so can you provide details of your implementation, including base/ incremental learning rate, epoch, etc?

Sorry for the delayed reply.
I set learning rate to 5e-5 and trained 1epoch for both base and incremental sessions in CIFAR-100.
