### ISSUE TITLE
Problem with dataset CIFAR100

### ISSUE THREAD

**Issue by pdt0609** [KHU-AGI/PriViLege#6]
Dear Authors,
I have no problem with datset CUB-200 and mini-imagenet, but there remains some size problems with cifar-100 that i cannot reproduce code.

`File "/PriViLege/dataloader/cifar100/cifar.py", line 124, in __init__
    self.data, self.targets = self.SelectfromDefault(self.data, self.targets, index)
  File "/PriViLege/dataloader/cifar100/cifar.py", line 138, in SelectfromDefault
    if data_tmp == []:
ValueError: operands could not be broadcast together with shapes (500,32,32,3) (0,) `

**Comment by pgh2874** [comment]
Since I cannot reproduce the error you mentioned, I think you might have revised some code after I released it. If this is the case, I need more information to address the issue, such as whether the error occurred in the base or incremental sessions, and which code was changed.

**Comment by guaguaxyf** [comment]
I meet this problem too, and I'm not edit any code?

**Comment by hongwei-zhao** [comment]
I meet this problem too, and I updated the code: 

![Image](https://github.com/user-attachments/assets/e42cdbdf-2c39-4bb2-936c-2961ab262825)

**Comment by Yongzhang-Tan** [comment]
Installing version 1.24.4 of numpy can solve this problem
