### ISSUE TITLE
problem of grad

### ISSUE THREAD

**Issue by guaguaxyf** [KHU-AGI/PriViLege#8]
Why after performing loss  tri.backward() show model.module.expert_prompt.grad = tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:0')
![image](https://github.com/user-attachments/assets/d7305900-aec7-4b17-9cd7-d0c4a15721b5)

**Comment by pgh2874** [comment]
https://github.com/KHU-AGI/PriViLege/issues/4#issuecomment-2222992527
It seems related to the version pytorch.
