### ISSUE TITLE
about result

### ISSUE THREAD

**Issue by guaguaxyf** [KHU-AGI/PriViLege#9]
![image](https://github.com/user-attachments/assets/72c150c0-eb3e-42bf-b44d-60416d912205)
I have some questions～ 1. Can you explain ABase, ALast, and Aavg specifically for the experimental results? What do the "+-" in the results refer to? Is the best result obtained at seed=1? 2. What is the function of the "replace_base_fc" operation?

**Comment by pgh2874** [comment]
We evaluated the performance by measuring the accuracy of the base session (ABase), the last session (ALast), and the average accuracy of all the sessions (AAvg). We conducted five simulations under different random seeds and reported the averages; the "+—" means the standard deviation from the five simulations.
I'm not sure what  "replace_base_fc" operation means. Please give me more details.

**Comment by guaguaxyf** [comment]
Thank you for your reply～For the problem of “replace_base_fc”, the following is the corresponding code:
![image](https://github.com/user-attachments/assets/9f9d0f96-52a9-4093-88c3-004a98a6972f)
![image](https://github.com/user-attachments/assets/130c2559-c4a3-45d5-959b-26be32f04caf)
In my experiments, this operation always resulted in a drop in Abase

**Comment by pgh2874** [comment]
As mentioned in paper, we replace the classifier with the prototype classifier. It has huge benefits on classifying at incremental session. Since the classifier is changed, the base session performance could be drop.

**Comment by guaguaxyf** [comment]
On cub200, epoch and learning rate are set to 5+3 and 2e-4 according to the paper, and seed is [1,2,3,4,5], but my output seems to be unable to reach the effect of the paper. May I ask what the problem is?
![image](https://github.com/user-attachments/assets/6852d655-36c1-4cb1-a069-0b9bd3459d85)

**Comment by pgh2874** [comment]
Sorry for the delayed response. I checked the table above, and it appears that the performance is slightly lower than the recorded results in the paper. However, considering the standard deviation across multiple seeds, the performance seems reasonable. If you want to improve the results to better reproduce the original performance, I suggest running the trials with a wider range of seeds (0–30). Also, keep in mind that the GPU can impact performance; I used a single GTX 3090 for my experiments. I hope this helps. Thank you for your interest in my paper!

**Comment by guaguaxyf** [comment]
![image](https://github.com/user-attachments/assets/41578876-9d16-4c5a-a1e8-4b5835ac03ed)
Thank you for your help many times！I re-set the seeds, but it seems that the result is still not satisfactory. If it is convenient, can you tell me which specific seeds are suitable? I also used the GTX 3090 for the experiment

**Comment by pgh2874** [comment]
![image](https://github.com/user-attachments/assets/d6646558-740b-46ea-a980-401016882a99)

I’m sharing the experiments I conducted for PriVilege using various seeds. It includes the final performance of PriVilege on CUB-200 and the results across different seeds. Rows in blue represent the selected seeds (2,10,12,14,15), while rows in red indicate the aggregated performance.

I hope this will be helpful to you.
